name: Docker Build & Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:


  build-push-prod-image:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push with commit hash tag
        run: |
          docker compose build
          docker compose push

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/app/on/ec2 # Navigate to your application directory on the EC2 instance
            # Pull the latest images and restart containers
            docker compose pull
            docker compose down
            docker compose up -d --remove-orphans
            # Replace 'docker compose' with 'docker-compose' if using older versions
