name: Deploy to EC2

on:
  push:
    branches: [ "main" ]
  workflow_run:
    workflows: [Test All Services]
    types:
    - completed
  workflow_dispatch: 

jobs:
  build-push-prod-image:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu # Navigate to your application directory on the EC2 instance
            # Pull the latest images and restart containers
            docker system prune -f
            docker compose pull
            docker compose down
            docker compose up -d --remove-orphans
            # Replace 'docker compose' with 'docker-compose' if using older versions

